### ISSUE TITLE
Assertion fail in qzCompress() when sometime, use QZ_DEFLATE_RAW format

### ISSUE THREAD

**Issue by danny0409** [intel/QATzip#50]
OS: Ubuntu 18.04.6 x86_64 Server
Kernel: 5.4.0-65
HW: Intel QuickAssist 8970
　
### QzSessionParams
direction: QZ_DIR_COMPRESS
data_fmt: QZ_DEFLATE_RAW
max_forks: 0

_other ... Default_
　
### Console output:
> ``qatzip.c:1687: qzCompressCrc: Assertion `*dest_len == sess->total_out' failed.``
　
### gdb backtrace
 ```
(gdb) bt
#0  0x00007ff4a51a8fb7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ff4a51aa921 in __GI_abort () at abort.c:79
#2  0x00007ff4a519a48a in __assert_fail_base (fmt=0x7ff4a5321750 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
     assertion=assertion@entry=0x7ff26acec331 "*dest_len == sess->total_out", file=file@entry=0x7ff26acec328 "qatzip.c",
     line=line@entry=1687, function=function@entry=0x7ff26acec6c0 <__PRETTY_FUNCTION__.6849> "qzCompressCrc") at assert.c:92
#3  0x00007ff4a519a502 in __GI___assert_fail (assertion=assertion@entry=0x7ff26acec331 "*dest_len == sess->total_out",
     file=file@entry=0x7ff26acec328 "qatzip.c", line=line@entry=1687,
     function=function@entry=0x7ff26acec6c0 <__PRETTY_FUNCTION__.6849> "qzCompressCrc") at assert.c:101
#4  0x00007ff26ace90f1 in qzCompressCrc (sess=sess@entry=0x7ff245b3b800, src=src@entry=0x7ff1a8c0b010 "",
     src_len=0x7ff2537fd8f0, dest=0x7ff0056b0010 "\354]\t`\023U\032~\223\206\022.\023<\353IЪqQ)\326u\213EH -\023,l=\351*J\261\002\301
     \213.\024-\352B\240T\023\306j\301\253\270\256ƃ5\353YE\245\350*)\b\004P)\340Q\320Ŋ\256\004\253R
     \217Ū\v\331\367\336\377\377i\337@\345Xtw\335|M\372\315\377\375\377;\346\275\067of^&-c̢\365pZ\323KKN\237\064\346Za\362\067
     ;,\213\343l\361:\343\364\254\276\327\217\037s\372\365\340e\032\377uh\337I\023\257u\217-+\351;\246\244tB߲1W\\3v2\023\340\211;\363\234\256
     \230\060\021l+c\275\222Ye\213\254&L*\233\060\361\264\353Ɩ"..., dest_len=0x7ff2537fd8f4, last=1, crc=<optimized out>) at qatzip.c:1687
#5  0x00007ff26ace9135 in qzCompress (sess=0x7ff245b3b800, src=0x7ff1a8c0b010 "", src_len=<optimized out>, dest=<optimized out>,
     dest_len=<optimized out>, last=<optimized out>) at qatzip.c:1524
#6  0x000055a0ca76ae10 in ft_compress_worker_func (seg_state=0x7ff24400d870, comp_state=0x7ff244132460) at migration/ft-message.c:945
#7  0x00007ff4a91d2c70 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ff4a91d22a5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ff4a55626db in start_thread (arg=0x7ff2537fe700) at pthread_create.c:463
#10 0x00007ff4a528b71f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```
　
### Update:
Initial understanding after testing, this situation occur **raw format compression** and **resl->status equal CPA_DC_VERIFY_ERROR**.

**Comment by cfzhu** [comment]
thank you for rising this issue, I think it is same problem as https://github.com/intel/QATzip/issues/47,  Would you like to try the latest version?
